version: '3.8'
services:
  # nestjs-prod:
  #   container_name: nestjs_cont_prod
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   environment:
  #     - NODE_ENV=production
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   ports:
  #     - 3001:3000

  nestjs-dev:
    image: nestjs_img:0.0.1
    container_name: nestjs_dev_cont
    env_file:
      - .env.development.local
    ports:
      - 3000:3000
    networks:
      - dev_network
    build:
      context: .
      dockerfile: Dockerfile.development.local
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres-dev

  postgres-dev:
    image: postgres:16
    container_name: postgres_dev_cont
    env_file:
      - .env.development.local
    ports:
      - "9999:5432"
    networks:
      - dev_network
    restart: always
    volumes:
      - postgres_db:/var/lib/postgresql/data

networks:
  dev_network:
    driver: bridge

volumes:
  postgres_db:
    driver: local
