version: '3.8'
services:
  # nestjs-prod:
  #   container_name: nestjs_cont_prod
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   environment:
  #     - NODE_ENV=production
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   ports:
  #     - 3001:3000

  postgres-dev:
    image: postgres:16
    container_name: postgres_dev_cont
    env_file:
      - .env
    ports:
      - "9999:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    # networks:
    #   - dev_network
    # volumes:
    #   - postgres_db:/var/lib/postgresql/data
    # depends_on:
    #   - nestjs-dev

  nestjs-dev:
    image: nestjs_img:0.0.1
    container_name: nestjs_dev_cont
    env_file:
      - .env
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      postgres-dev:
        condition: service_healthy
    # networks:
    #   - dev_network

# networks:
#   dev_network:
#     driver: bridge

# volumes:
#   postgres_db:
#     driver: local
